import Head from "next/head";
import { useState } from "react";
import SearchInput from "../components/SearchInput";
import ResultTable from "../components/ResultTable";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [showTable, setShowTable] = useState(false);
  const [showError, setShowError] = useState(false);

  const handleSearch = (input) => {
    if (input.trim() === "") return;
    setShowTable(!showTable);
    console.log(input);
  };

  return (
    <div className={styles.pageContainer}>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchInput handleSearch={handleSearch} />
      {showTable ? <ResultTable /> : null}
    </div>
  );
}
